### PR TITLE
Fix documentation for processing of categories on update

### PR DESCRIPTION
**Pull request by pascalberger**
Based on https://github.com/pascalberger/Cake.AddinDiscoverer/blob/6c282e8ab67f88b89862569709df4e6d931ebdc8/Source/Cake.AddinDiscoverer/Steps/SynchronizeYamlStep.cs#L259 categories are not updated for existing addins. Fix documentation to match implementation.

### CODE REVIEW

**Comment by Jericho** [comment]
???

**Comment by Jericho** [comment]
I guess you could say that we don't really update the categories. We merely "normalize" the content of this attribute (for example, we make sure each category is prepended with a dash, each category is lower cased, etc.). Kinda like the description attribute which we don't update but we normalize line endings.

**Comment by pascalberger** [comment]
> ???

It is important to know exactly what addin discoverer does. As you mentioned in another issue, attributes handled by addin discoverer should not be updated manually. In case of categorie they need too be updated manually though if they are changed (e.g. in the case where we recently blacklisted the cake-contrib category).   

> I guess you can argue that we don't really update the categories, we merely "normalize" the content of this attribute (for example, we make sure each category is prepended with a dash, each category is lower cased, etc.). Kinda like the description attribute which we don't update but we normalize line endings. So in that sense you are right, we don't update this attribute.

I updated to `Only content normalized`

**Review by Jericho — APPROVED** [review]
Looks good to me!

**Pull request merged**
